/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TicketTierService } from "../ticketTier.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TicketTierCreateInput } from "./TicketTierCreateInput";
import { TicketTier } from "./TicketTier";
import { TicketTierFindManyArgs } from "./TicketTierFindManyArgs";
import { TicketTierWhereUniqueInput } from "./TicketTierWhereUniqueInput";
import { TicketTierUpdateInput } from "./TicketTierUpdateInput";
import { PurchasedTicketFindManyArgs } from "../../purchasedTicket/base/PurchasedTicketFindManyArgs";
import { PurchasedTicket } from "../../purchasedTicket/base/PurchasedTicket";
import { PurchasedTicketWhereUniqueInput } from "../../purchasedTicket/base/PurchasedTicketWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TicketTierControllerBase {
  constructor(
    protected readonly service: TicketTierService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TicketTier })
  @nestAccessControl.UseRoles({
    resource: "TicketTier",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: TicketTierCreateInput,
  })
  async createTicketTier(
    @common.Body() data: TicketTierCreateInput
  ): Promise<TicketTier> {
    return await this.service.createTicketTier({
      data: {
        ...data,

        event: data.event
          ? {
              connect: data.event,
            }
          : undefined,
      },
      select: {
        amountOnSale: true,
        amountSold: true,
        createdAt: true,
        endDate: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        purchasePrice: true,
        startDate: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TicketTier] })
  @ApiNestedQuery(TicketTierFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TicketTier",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ticketTiers(@common.Req() request: Request): Promise<TicketTier[]> {
    const args = plainToClass(TicketTierFindManyArgs, request.query);
    return this.service.ticketTiers({
      ...args,
      select: {
        amountOnSale: true,
        amountSold: true,
        createdAt: true,
        endDate: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        purchasePrice: true,
        startDate: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TicketTier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketTier",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ticketTier(
    @common.Param() params: TicketTierWhereUniqueInput
  ): Promise<TicketTier | null> {
    const result = await this.service.ticketTier({
      where: params,
      select: {
        amountOnSale: true,
        amountSold: true,
        createdAt: true,
        endDate: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        purchasePrice: true,
        startDate: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TicketTier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketTier",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: TicketTierUpdateInput,
  })
  async updateTicketTier(
    @common.Param() params: TicketTierWhereUniqueInput,
    @common.Body() data: TicketTierUpdateInput
  ): Promise<TicketTier | null> {
    try {
      return await this.service.updateTicketTier({
        where: params,
        data: {
          ...data,

          event: data.event
            ? {
                connect: data.event,
              }
            : undefined,
        },
        select: {
          amountOnSale: true,
          amountSold: true,
          createdAt: true,
          endDate: true,

          event: {
            select: {
              id: true,
            },
          },

          id: true,
          purchasePrice: true,
          startDate: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TicketTier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketTier",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTicketTier(
    @common.Param() params: TicketTierWhereUniqueInput
  ): Promise<TicketTier | null> {
    try {
      return await this.service.deleteTicketTier({
        where: params,
        select: {
          amountOnSale: true,
          amountSold: true,
          createdAt: true,
          endDate: true,

          event: {
            select: {
              id: true,
            },
          },

          id: true,
          purchasePrice: true,
          startDate: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/purchasedTickets")
  @ApiNestedQuery(PurchasedTicketFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PurchasedTicket",
    action: "read",
    possession: "any",
  })
  async findPurchasedTickets(
    @common.Req() request: Request,
    @common.Param() params: TicketTierWhereUniqueInput
  ): Promise<PurchasedTicket[]> {
    const query = plainToClass(PurchasedTicketFindManyArgs, request.query);
    const results = await this.service.findPurchasedTickets(params.id, {
      ...query,
      select: {
        code: true,
        createdAt: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        status: true,

        ticketTier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/purchasedTickets")
  @nestAccessControl.UseRoles({
    resource: "TicketTier",
    action: "update",
    possession: "any",
  })
  async connectPurchasedTickets(
    @common.Param() params: TicketTierWhereUniqueInput,
    @common.Body() body: PurchasedTicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      purchasedTickets: {
        connect: body,
      },
    };
    await this.service.updateTicketTier({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/purchasedTickets")
  @nestAccessControl.UseRoles({
    resource: "TicketTier",
    action: "update",
    possession: "any",
  })
  async updatePurchasedTickets(
    @common.Param() params: TicketTierWhereUniqueInput,
    @common.Body() body: PurchasedTicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      purchasedTickets: {
        set: body,
      },
    };
    await this.service.updateTicketTier({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/purchasedTickets")
  @nestAccessControl.UseRoles({
    resource: "TicketTier",
    action: "update",
    possession: "any",
  })
  async disconnectPurchasedTickets(
    @common.Param() params: TicketTierWhereUniqueInput,
    @common.Body() body: PurchasedTicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      purchasedTickets: {
        disconnect: body,
      },
    };
    await this.service.updateTicketTier({
      where: params,
      data,
      select: { id: true },
    });
  }
}
